[server]
headless = true
port = $PORT
enableCORS = false
enableWebsocketCompression = false

[theme]
primaryColor = "#F39C12"
backgroundColor = "#2C3E50"
secondaryBackgroundColor = "#34495E"
textColor = "#ECF0F1"
